version: '3'
services:
  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    
    environment:
      MYSQL_DATABASE: quimicaUam
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "6033:3306"
    
  web:
    image: php:7.3-apache
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./Quimica:/var/www/html
      
    links:
      - mariadb